sudo: required

# languages
language: python
python:
    - "3.6"

services:
    - docker

before_install:
    - docker pull firedrakeproject/firedrake
    - export PYTHONPATH=$(pwd):$PYTHONPATH
script: 
    - travis_wait 20 docker build .
