# languages
language: python
python:
    - "2.7"
addons:
  apt:
    packages:
        - build-essential
        - cmake
        - gfortran
        - libblas-dev
        - liblapack-dev
        - libmpich-dev
        - mercurial
        - mpich
        - python3-pip
        - python3-tk
        - python3-venv
        - libboost-dev      
# command to run scripts
os:
  - linux

before_install:
  - pip install -U pip
  - pip install -U virtualenv

install:
  - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
  - travis wait 30 python3 ./firedrake-install --disable-ssh --minimal-petsc
  - . ./firedrake/bin/activate
  - pip install -r requirements.txt
