# languages
language: python
python:
    - "3.6"

addons:
  apt:
    packages:
        - build-essential
        - cmake
        - gfortran
        - libblas-dev
        - liblapack-dev
        - libmpich-dev
        - mercurial
        - mpich
        - python3-pip
        - python3-tk
        - python3-venv
        - libboost-dev

before_install:
    - pip install -U pip
    - pip install -U virtualenv
      
# command to install dependencies
install:
    - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
    - python3 firedrake-install
    - ./firedrake/bin/activate
    - pip install -r requirements.txt

# command to run scripts
os:
  - linux

env:
  global:
    - CC=mpicc
    # HACK: travis runs 12.04 for which the CMAKE version is too old to
    # build Eigen, let PETSc build it instead. Fixed now.
    - PETSC_CONFIGURE_OPTIONS="--download-eigen=0"

before_install:
  - pip install -U pip
  - pip install -U virtualenv

install:
  - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
  - python3 firedrake-install 
  - source firedrake/bin/activate
  - pip install -r requirements.txt
