sudo: required

# languages
language: python
python:
    - "3.6"
    - "2.7"

services:
    - docker

before_install:
    - docker pull firedrakeproject/firedrake

script: 
    - travis_wait 20 docker build .
