language: python
python:
    - "3.6"

# command to install dependencies
install:
    - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
    - python3 firedrake-install
    - ./firedrake/bin/activate
    - pip install -r requirements.txt

# command to run scripts

