sudo: required

# languages
language: python
python:
    - "3.6"

services:
    - docker

before_install:
    - docker pull firedrakeproject/firedrake

script: 
    - travis_wait 20 docker build .
    - cd acse/fireframe/test
    - pytest tests.py
